// Code generated by "stringer -type=ContainerStatus"; DO NOT EDIT

package main

import "fmt"

const _ContainerStatus_name = "DEADNOT_RUNNINGRUNNINGSTARTINGREADY"

var _ContainerStatus_index = [...]uint8{0, 4, 15, 22, 30, 35}

func (i ContainerStatus) String() string {
	if i < 0 || i >= ContainerStatus(len(_ContainerStatus_index)-1) {
		return fmt.Sprintf("ContainerStatus(%d)", i)
	}
	return _ContainerStatus_name[_ContainerStatus_index[i]:_ContainerStatus_index[i+1]]
}
